### ISSUE TITLE
Shutdown TiDB gracefully

### ISSUE THREAD

**Issue by lerencao** [pingcap/tidb-ansible#506]
TiDB only stops gracefully when `QUIT` signal received. See:

``` go
func setupSignalHandler() {
	sc := make(chan os.Signal, 1)
	signal.Notify(sc,
		syscall.SIGHUP,
		syscall.SIGINT,
		syscall.SIGTERM,
		syscall.SIGQUIT)

	go func() {
		sig := <-sc
		log.Infof("Got signal [%s] to exit.", sig)
		if sig == syscall.SIGQUIT {
			graceful = true
		}

		if xsvr != nil {
			xsvr.Close() // Should close xserver before server.
		}
		svr.Close()
	}()
}
```

However, the supervise deployment stops server by sending `TERM` signal.

Conflict exists here. 

Either this repo or the tidb repo should take care of this.

**Comment by tiancaiamao** [comment]
Graceful shutdown will wait all sessions to be idle and then exit. If TiDB is running a big query, or DDL add index for example, it will never shut down until the operation finish.

This behavior is harmful when rolling update. If the old version and the new version TiDB binary coexists, it may results in a disaster. (For example, the old server think it's still a leader, but it can't communicate with the newer, since protocol change. Countless other cases you may think)

So, the supervise deployment doesn't stop the server using graceful shutdown, it send `TERM` signal to make sure the TiDB server will be killed.

@lerencao

**Comment by tiancaiamao** [comment]
> So we just cannot do graceful shutdown? That sounds weird.

You can do graceful shutdown, as long as you know what you're doing.
The feature is not the problem on its own.

> Could you give some more details on protocol change?

I'll not give more details, It's just an example.
When I said that, I actually mean: different version TiDB maybe can't work together, that's by design.

> AFAIK, graceful shutdown only close port, stop receiving any new conns.
every other structures still remain unchanged, and existed conns are stopped once dispatching request is finished.

Exactly. 

> Of course, the current dispatching request may pending for a while

That's the problem, we can't control how long about the "for a while".
Sometimes we need a determinate result, that the TiDB is killed.

> however, it's a rare case.

It's totally out of our control.

Rolling update require TiDB to be killed, graceful shutdown can't guarantee that, so it doesn't use the feature. Is it clear?

The feature itself is okay, but the caller have to keep in mind when to use it.
A potential improvement of tidb-ansible maybe try to graceful shutdown TiDB first, if it's not success within a while, use `kill -s TERM`.

@lerencao

**Comment by lerencao** [comment]
@tiancaiamao thanks !

When I said `cannot`, I actually mean graceful shutdown is not the default action, which I thought it should be. As non-graceful shutdown still cause client error.

From the perspective of version compatibility, it's fair enough because many users doesn't give precheck on it.

As for the details on protocol change, well, forget it. Trust you guys do details well. :)

It's may be better if conns can be given some time to close themselves in `GracefulDown()` method, say 5s (a configurable option here), then force quit.
